"use client"
import 'bootstrap/dist/css/bootstrap.min.css';
import Link from 'next/link';
import React from 'react';
import { Container, Nav, Navbar } from 'react-bootstrap';
import "./globals.css"
import "../App.css";
import Image from 'next/image';
import logo from "../images/corazon-letras blancas.png"



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}



export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Navbar bg='primary' expand="lg" sticky='top' variant="dark">
          <Container fluid>
            <Navbar.Toggle aria-controls="navbarScroll" />
            <Navbar.Collapse>


              <Nav
                className="mx-auto my-2 my-lg-0"
                style={{ fontSize: "1.5rem" }}
                navbarScroll
              >
                <Link className="nav-link" href="/" >Inicio</Link>
                <Link className="nav-link" href="/empresas">Comercio </Link>
                <Link className="nav-link" href="/turismo">Turismo</Link>
                <Link className="nav-link" href="/blog">Eventos y Festividades</Link>
                <Link className="nav-link" href="/galeria">Galería</Link>
                <Link className="nav-link" href="/registro">Registro comercial</Link>
              </Nav>
            </Navbar.Collapse>

          </Container>
        </Navbar>
          {children}
        <footer className='bg-[#037ccb] flex flex-col gap-4 py-6 text-white' >
          <ul className=' flex justify-between md:w-4/6 w-full px-8 text-semibold text-xl mx-auto'>
            <li><Link href="blog" className='nav-link'>Blog</Link></li>
            <li><Link href="galeria" className='nav-link'>Galeria</Link></li>
            <li><Link href='registro' className='nav-link'>Registro</Link></li>
            <li><Link href='turismo' className='nav-link'>Turismo</Link></li>
          </ul>
          <div>
            <a href='https://www.facebook.com/PrensaMonterrey'><Image width={50} height={50} src={logo} /></a>
          </div>
        </footer>
      </body>
    </html>
  )
}
