"use client"
import 'bootstrap/dist/css/bootstrap.min.css';
import Link from 'next/link';
import React from 'react';
import { Container, Nav, Navbar } from 'react-bootstrap';
import "./globals.css"
import "../App.css";
import corazonW from "../images/corazon-letras blancas.png";
import Image from 'next/image';
import logo from "../images/corazon-letras blancas.png"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar bg='primary' expand="lg" sticky='top' variant="dark">
          <Container fluid>
            <Navbar.Brand href="#"><Image src={corazonW} alt="Logo" width={50} height={50} /></Navbar.Brand>
            <Navbar.Toggle aria-controls="navbarScroll" />
            <Navbar.Collapse>


              <Nav
                className="mx-auto my-2 my-lg-0"
                style={{ fontSize: "1.5rem" }}
                navbarScroll
              >
                <Link className="nav-link" href="/" >Inicio</Link>
                <Link className="nav-link" href="empresas">Comercio </Link>
                <Link className="nav-link" href="turismo">Turismo</Link>
                <Link className="nav-link" href="blog">Eventos y Festividades</Link>
                <Link className="nav-link" href="galeria">Galería</Link>
                <Link className="nav-link" href="registro">Registro comercial</Link>
              </Nav>
            </Navbar.Collapse>

          </Container>
          </Navbar>
          {children}
          <footer className='bg-[#037ccb]' >
                <div>
                    <a><Image width={50} height={50} src={logo} /></a>
                </div>

                <div>
                    <ul>
                        <li><Link href="blog" className='nav-link'>Blog</Link></li>
                        <li><Link href="galeria" className='nav-link'>Galeria</Link></li>
                        <li><Link href='registro' className='nav-link'>Registro</Link></li>
                        <li><Link href='turismo' className='nav-link'>Turismo</Link></li>
                    </ul>
                </div>
                <div>

                    <ul>
                        <li><a href='#' className='nav-link'>Políticas de privacidad </a></li>
                        <li><a href='#' className='nav-link'>Aviso Legal</a></li>
                        <li><a href='#' className='nav-link'>Acerca de las Cookies</a></li>
                    </ul>
                </div>
            </footer>
          </body>
    </html>
  )
}
